export const CURRENCIES_REQUEST = 'CURRENCIES_REQUEST'
export const CURRENCIES_FAIL = 'CURRENCIES_FAIL'
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'

export const PRODUCTS_BY_CATEGORY_REQUEST = 'PRODUCTS_BY_CATEGORY_REQUEST'
export const PRODUCTS_BY_CATEGORY_FAIL = 'PRODUCTS_BY_CATEGORY_FAIL'
export const PRODUCTS_BY_CATEGORY_SUCCESS = 'PRODUCTS_BY_CATEGORY_SUCCESS'
