export const CURRENCIES_REQUEST = 'CURRENCIES_REQUEST'
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS'
export const CURRENCIES_FAIL = 'CURRENCIES_FAIL'

export const SHOW_HIDE_CURRENCY = 'SHOW_HIDE_CURRENCY'

// DEMO
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
